version: '3'
services:
  postgres_db22:
    image: postgres:14-alpine
    container_name: postgres22
    environment:
      - POSTGRES_PASSWORD=LuisBandera123
      - POSTGRES_DB=musirockstars_db
      - POSTGRES_USER=luis_banderas
    ports:
      - 10022:5522
    volumes:
      - /home/luis_banderas/postgres:/usr/src/postgres
    networks:
      - our-library-net
    command: -p 5522

  web22:
    build: .
    image: my-django-image22:2.0.0
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8022"
    container_name: django22
    depends_on: 
      - postgres_db22
    environment:
      - PSQL_DBNAME=musirockstars_db
      - PSQL_USERNAME=luis_banderas
      - PSQL_PASS=LuisBandera123
      - PSQL_HOST=postgres_db22
      - PSQL_PORT=5522
      - JWT_TOKEN_TIME=120
    volumes:
      - /home/luis_banderas/django/Hazel-pytest:/usr/src/django/library
    ports:
      - 9022:8022
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge
